import { Actions, Hero, Section, Closing, Breadcrumb, EditorialRows } from '@/app/components/Corporate';
import { generateMetadata } from '@/lib/seo';
export const metadata = generateMetadata({title:'Implementation Evidence',description:'Review ProHotelAI implementation evidence: Hotel Digital Brain, guest-to-operations workflows, Hotel Commerce, management intelligence and supported integrations.',path:'/case-studies'});
export default function Evidence() { return <>
  <Breadcrumb title="Implementation Evidence" path="/case-studies" />
  <Hero eyebrow="Evidence / Implementation" title={<>Evaluate the work.<br /><em>Examine the evidence.</em></>} copy="A credible implementation connects product capability with the hotel’s actual workflows. We keep that distinction clear." scene="operations"><Actions primary="Review the product fact sheet" href="https://prohotelai.com/fact-sheet" /></Hero>
  <Section eyebrow="Documented product capabilities" title="ProHotelAI implementation evidence."><p className="section-lead">These implementation areas are documented in the official product resources. Review the supported workflow and the evidence available in your hotel’s configuration.</p><EditorialRows items={[
    {title:'Hotel Digital Brain',copy:'Governed hotel knowledge, source ownership and approved corrections provide usable operational context. Review how eligible knowledge and authorised updates inform answers and actions.',href:'https://prohotelai.com/hotel-digital-brain',link:'Review hotel knowledge'},
    {title:'Guest → Operations',copy:'Supported guest intent becomes structured, accountable staff work with department ownership and visible progress. Review the handoff from guest assistance to staff fulfilment.',href:'https://prohotelai.com/hotel-operations',link:'Review the workflow'},
    {title:'Commerce',copy:'Configured hotel services, dining and approved partner experiences become relevant options in the guest journey. Guests review the offering before confirming supported bookings.',href:'https://prohotelai.com/revenue-intelligence',link:'Review hotel commerce'},
    {title:'Management Intelligence',copy:'Operational evidence and AI Reports help authorised managers investigate issues and review improvements. Findings and knowledge corrections remain subject to permissions and human review.',href:'https://prohotelai.com/hotel-intelligence',link:'Review management intelligence'},
    {title:'PMS & Integration Boundary',copy:'Existing hotel systems retain their authority. ProHotelAI acts as a governed intelligence and operational layer through supported integration boundaries, with connections defined by hotel configuration and available connectors.',href:'https://prohotelai.com/integrations',link:'Review integration boundaries'},
  ]} /><p className="corporate-note">PROINVEST GLOBAL provides the corporate context; prohotelai.com maintains product-specific detail. Capabilities depend on configured services, permissions and supported connectors.</p></Section>
  <Section eyebrow="Customer case studies" title="Results require a documented implementation."><p className="section-lead">We are not publishing named customer case studies or quantified customer outcomes on this page yet.</p><p>For an evaluation, request a demonstration of the configured workflow, supported integration, permissions and operational evidence relevant to your property.</p></Section>
  <Closing title="See the workflow that matters to your hotel." />
</>; }
